import Combine
import Foundation

struct ClipboardSnippet: Identifiable, Equatable {
    let id: UUID
    let text: String
}

/// A best-effort exclusion of explicitly marked secret/transient pasteboard
/// items. Unmarked passwords cannot be reliably identified, so capture is
/// ALWAYS a user-initiated action and remains disabled until opt-in.
enum ClipboardCapturePolicy {
    static let maximumCharacters = 500

    static func permits(types: [String]) -> Bool {
        !types.contains { type in
            let lower = type.lowercased()
            return lower.contains("concealed")
                || lower.contains("transient")
                || lower.contains("autogenerated")
                || lower.contains("password")
                || lower.contains("onepassword")
                || lower.contains("1password")
                || lower == "public.file-url"
        }
    }

    static func safeText(_ text: String?) -> String? {
        guard let text else { return nil }
        let scalars = text.unicodeScalars.compactMap { scalar -> Unicode.Scalar? in
            let code = scalar.value
            let bidi = (0x202A...0x202E).contains(code)
                || (0x2066...0x2069).contains(code)
                || code == 0x200E || code == 0x200F || code == 0x061C
            if bidi { return nil }
            if code == 10 || code == 13 || code == 9 { return " " }
            if CharacterSet.controlCharacters.contains(scalar) { return nil }
            return scalar
        }
        let cleaned = String(String.UnicodeScalarView(scalars))
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return nil }
        return String(cleaned.prefix(maximumCharacters))
    }
}

/// RAM-only snippets. No background pasteboard watching, file persistence,
/// connector publishing or automatic write back to the clipboard.
@MainActor
final class TransientClipboardHistory: ObservableObject {
    static let maximumItems = 5
    @Published private(set) var snippets: [ClipboardSnippet] = []
    @Published private(set) var notice: String?
    private(set) var enabled = false

    func configure(enabled newValue: Bool) {
        guard enabled != newValue else { return }
        enabled = newValue
        if !newValue { clear() }
    }

    func rejectPrivate() {
        guard enabled else { return }
        notice = "This clipboard item is marked private or temporary."
    }

    func capture(_ text: String?, types: [String]) {
        guard enabled else { return }
        guard ClipboardCapturePolicy.permits(types: types) else {
            rejectPrivate()
            return
        }
        guard let safe = ClipboardCapturePolicy.safeText(text) else {
            notice = "No plain text available to save."
            return
        }
        if snippets.contains(where: { $0.text == safe }) {
            notice = "Already saved in this session."
            return
        }
        snippets.insert(ClipboardSnippet(id: UUID(), text: safe), at: 0)
        if snippets.count > Self.maximumItems {
            snippets.removeLast(snippets.count - Self.maximumItems)
        }
        notice = nil
    }

    func remove(id: UUID) {
        snippets.removeAll { $0.id == id }
    }

    func clear() {
        snippets.removeAll()
        notice = nil
    }
}
