import Foundation
import PixelCompanionCore
@testable import PixelCompanion
import XCTest

final class TransientClipboardHistoryTests: XCTestCase {
    func testKnownSensitiveAndTransientMarkersAreRejected() {
        let secretTypes = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
            "com.1password.private",
            "public.file-url"
        ]
        for type in secretTypes {
            XCTAssertFalse(ClipboardCapturePolicy.permits(types: ["public.utf8-plain-text", type]))
        }
        XCTAssertTrue(ClipboardCapturePolicy.permits(types: ["public.utf8-plain-text"]))
    }

    func testCleanedTextIsBoundedAndRemovesSpoofingControls() {
        XCTAssertEqual(ClipboardCapturePolicy.safeText("\nHi\u{202E}\tworld\u{2066}"), "Hi world")
        XCTAssertNil(ClipboardCapturePolicy.safeText("\n\t\u{202E}"))
        XCTAssertEqual(
            ClipboardCapturePolicy.safeText(String(repeating: "x", count: 900))?.count,
            ClipboardCapturePolicy.maximumCharacters
        )
    }

    @MainActor
    func testDisabledCaptureDoesNotReadOrSave() {
        let history = TransientClipboardHistory()
        history.capture("hello", types: ["public.utf8-plain-text"])
        XCTAssertTrue(history.snippets.isEmpty)
        XCTAssertFalse(history.enabled)
    }

    @MainActor
    func testEnabledStoresOnlyDistinctFiveRecentItems() {
        let history = TransientClipboardHistory()
        history.configure(enabled: true)
        for number in 1...7 {
            history.capture("value \(number)", types: ["public.utf8-plain-text"])
        }
        XCTAssertEqual(history.snippets.count, 5)
        XCTAssertEqual(history.snippets[0].text, "value 7")
        XCTAssertEqual(history.snippets.last?.text, "value 3")
        history.capture("value 7", types: [])
        XCTAssertEqual(history.snippets.count, 5)
    }

    @MainActor
    func testConcealedClipCannotBeCaptured() {
        let history = TransientClipboardHistory()
        history.configure(enabled: true)
        history.capture("secret", types: ["org.nspasteboard.ConcealedType"])
        XCTAssertTrue(history.snippets.isEmpty)
        XCTAssertNotNil(history.notice)
    }

    @MainActor
    func testRemoveClearAndDisableForgetAllText() {
        let history = TransientClipboardHistory()
        history.configure(enabled: true)
        history.capture("first", types: [])
        history.capture("second", types: [])
        history.remove(id: history.snippets[0].id)
        XCTAssertEqual(history.snippets.count, 1)
        history.clear()
        XCTAssertTrue(history.snippets.isEmpty)
        history.capture("third", types: [])
        history.configure(enabled: false)
        XCTAssertTrue(history.snippets.isEmpty)
        XCTAssertNil(history.notice)
    }

    func testClipboardOffByDefaultAndResets() {
        let suite = "ClipboardHistory-" + UUID().uuidString
        let defaults = UserDefaults(suiteName: suite)!
        defer { defaults.removePersistentDomain(forName: suite) }
        let store = SettingsStore(defaults: defaults)
        XCTAssertFalse(store.clipboardHistoryEnabled)
        store.clipboardHistoryEnabled = true
        XCTAssertTrue(SettingsStore(defaults: defaults).clipboardHistoryEnabled)
        XCTAssertFalse(store.fileShelfEnabled)
        store.reset()
        XCTAssertFalse(store.clipboardHistoryEnabled)
    }
}
